apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: eklav/fb-auth
        imagePullPolicy: Never
        env:
          # - name: JWT_KEY
          #   value: asdf
          - name: MONGO_URI
            value: 'mongodb://auth-mongodb-service:27017/auth'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
  - name: auth-port
    protocol: TCP
    port: 3000
    targetPort: 3000

